version: '3.1'

services:
    mongo:
        image: mongo:4.2
        container_name: mongodb
        restart: unless-stopped
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: default
        volumes:
          - ./data:/data/db
        ports:
          - "127.0.0.1:27017:27017"