version: '2'
services:
    vault:
      image: vault:1.5.2
      container_name: vault
      restart: unless-stopped
      volumes:
        - ./data:/vault/file:rw
        - ./config:/vault/config:rw
      cap_add:
        - IPC_LOCK
      network_mode: bridge
      environment:
        - VAULT_ADDR=http://0.0.0.0:8200
        - VAULT_API_ADDR=http://0.0.0.0:8200
        - VAULT_ADDRESS=http://0.0.0.0:8200
      entrypoint: vault server -config=/vault/config/vault.json
      ports: 
        - "8200:8200"